*.test targets and messages implemented

diff --git a/test/Makefile b/test/Makefile
--- a/test/Makefile
+++ b/test/Makefile
@@ -18,30 +18,66 @@ GECCOPRG:=$(CURDIR)/$(topdir)/gecco/$(bindir)/gecco.x
 .NOTPARALLEL:
 
 .PHONY: all essential special extended res_clean out_clean err_clean clean essential.res special.res extended.res all.res
-.PRECIOUS: all essential extended special
+.PRECIOUS: all essential extended special delscr 
+
+
+
 
 #entry targets
-all: all.res $(GECCOPRG)
-	@rmdir $(SCRDIR) || echo "could not remove scratch directory: "$(SCRDIR)" please remove by hand."
 
-essential: essential.res $(GECCOPRG)
-	@rmdir $(SCRDIR) || echo "could not remove scratch directory: "$(SCRDIR)" please remove by hand."
+%.clean :
+	@ rm -f $(basename $@).err $(basename $@).out $(basename $@).res
 
-extended:  extended.res $(GECCOPRG)
-	@rmdir $(SCRDIR) || echo "could not remove scratch directory: "$(SCRDIR)" please remove by hand."
+%.test: $(GECCOPRG) | %.clean
+	@-rm -f $(basename $@).err
+	@$(MAKE) -f Makefile --no-print-directory mkscr
+	@-$(MAKE) -f Makefile.parallel --no-print-directory $(basename $@).res
+	@-$(MAKE) -f Makefile --no-print-directory delscr
+	@. ./message.sh ;\
+	print_all $(basename $@).err ;\
+	print_summary $(basename $@).err 
 
-special:   special.res $(GECCOPRG)
-	@rmdir $(SCRDIR) || echo "could not remove scratch directory: "$(SCRDIR)" please remove by hand."
+all:  $(GECCOPRG)
+	@$(MAKE) -f Makefile --no-print-directory mkscr
+	@-$(MAKE) -f Makefile --no-print-directory all.res
+	@-$(MAKE) -f Makefile --no-print-directory delscr
+
+essential:  $(GECCOPRG)
+	@$(MAKE) -f Makefile --no-print-directory mkscr
+	@-$(MAKE) -f Makefile --no-print-directory essential.res
+	@-$(MAKE) -f Makefile --no-print-directory delscr
+
+extended:  $(GECCOPRG)
+	@$(MAKE) -f Makefile --no-print-directory mkscr
+	@-$(MAKE) -f Makefile --no-print-directory extended.res
+	@-$(MAKE) -f Makefile --no-print-directory delscr
+
+special:   $(GECCOPRG)
+	@$(MAKE) -f Makefile --no-print-directory mkscr
+	@-$(MAKE) -f Makefile --no-print-directory special.res
+	@-$(MAKE) -f Makefile --no-print-directory delscr
 
 
 #targets to run the test (defined in Makefile.parallel) , print summary and clean up
+
+
+essential_tests:=$(wildcard *.e.chk)
+extended_tests:=$(wildcard *.x.chk)
+special_tests:=$(wildcard *.s.chk)
+essential_outputs:=$(addsuffix .out, $(basename $(essential_tests)))
+extended_outputs:=$(addsuffix .out, $(basename $(extended_tests)))
+special_outputs:=$(addsuffix .out, $(basename $(special_tests)))
+essential_results:=$(addsuffix .res, $(basename $(essential_tests)))
+extended_results:=$(addsuffix .res, $(basename $(extended_tests)))
+special_results:=$(addsuffix .res, $(basename $(special_tests)))
+
 
 export SCRDIR 
 export GECCOPRG
 
 all.res: $(GECCOPRG)
 	@rm -f *.err ;\
-	$(MAKE) -f Makefile.parallel all;\
+	$(MAKE) -f Makefile.parallel $(essential_results) $(extended_results) $(special_results);\
 	echo "Result for whole suite:" ;\
 	. ./message.sh ;\
 	print_all *.err |tee all.res ;\
@@ -49,7 +85,7 @@ all.res: $(GECCOPRG)
 
 essential.res: $(GECCOPRG)
 	@rm -f *.e.err ;\
-	$(MAKE) -f Makefile.parallel essential;\
+	$(MAKE) -f Makefile.parallel $(essential_results);\
 	echo "Result for essential test set:" ;\
 	. ./message.sh ;\
 	print_all *.e.err |tee essential.res ;\
@@ -58,7 +94,7 @@ essential.res: $(GECCOPRG)
 
 extended.res:   $(GECCOPRG)
 	@rm -f *.x.err;\
-	$(MAKE) -f Makefile.parallel extended;\
+	$(MAKE) -f Makefile.parallel $(extended_results);\
 	echo "Result for extended test set:" ;\
 	. ./message.sh ;\
 	print_all *.x.err |tee extended.res ;\
@@ -67,7 +103,7 @@ extended.res:   $(GECCOPRG)
 
 special.res:  $(GECCOPRG) 
 	@rm -f *.s.err ;\
-	$(MAKE) -f Makefile.parallel special;\
+	$(MAKE) -f Makefile.parallel $(special_results);\
 	echo "Result for special test set:" ;\
 	. ./message.sh ;\
 	print_all *.s.err |tee special.res ;\
@@ -86,4 +122,13 @@ out_clean:
 	rm -f *.out 
 
 clean:	err_clean res_clean out_clean
+
+delscr:
+	@rmdir $(SCRDIR) || echo "could not remove scratch directory: "$(SCRDIR)" please remove by hand."
+
+mkscr:       # is removed in the toplevel targets in the other Makefile
+	@if [ ! -d $(SCRDIR) ];\
+	then\
+	  mkdir $(SCRDIR);\
+	fi;
 
diff --git a/test/Makefile.parallel b/test/Makefile.parallel
--- a/test/Makefile.parallel
+++ b/test/Makefile.parallel
@@ -1,13 +1,24 @@
 
 # some new rules (must be defined here BEFORE the objects)
 
-%.res : %.out
-	@set -e ; $(CHECK) $(CHECKFLAGS) $(basename $<) 1>>  $(basename $<).sum 2>&1 \
-	|| echo "!!ERROR!! test "$(basename $<)" failed. Output in "$(basename $<).out" ; error message in "$(basename $<).sum\
-	&& echo $(basename $<)" was successfull."
+%.res : %.out    
+	@if $(CHECK) $(CHECKFLAGS) $(basename $<) 1>>  $(basename $<).sum 2>&1  ;\
+	then \
+	 echo "test "$(basename $<)" was successful." ;\
+	else \
+	 echo "!!ERROR!! test "$(basename $<)" failed.;  Output: "$(basename $<).out";  Error message: "$(basename $<).sum ;\
+	fi
 
-%.out : %.chk $(GECCOPRG) |mkscr
-	@set -e ; $(RUNTEST) $(RUNFLAGS) $(basename $<) &> $(basename $<).sum || echo "running "$(basename $<)" failed. for more information see:"$(basename $<).sum
+
+#=$?;\
+
+%.out : %.chk $(GECCOPRG) 
+	@ if  $(RUNTEST) $(RUNFLAGS) $(basename $<) &> $(basename $<).sum ;\
+	then \
+	 echo $(basename $<)" ran successfully";\
+	else\
+	 echo "!!ERROR!! running "$(basename $<)" failed. Output: "$(basename $<).out"  Error message: "$(basename $<).sum ;\
+	fi
 
 
 
@@ -25,28 +36,9 @@ else
 endif
 CHECKFLAGS:=-c
 
-essential_tests:=$(wildcard *.e.chk)
-extended_tests:=$(wildcard *.x.chk)
-special_tests:=$(wildcard *.s.chk)
-essential_outputs:=$(addsuffix .out, $(basename $(essential_tests)))
-extended_outputs:=$(addsuffix .out, $(basename $(extended_tests)))
-special_outputs:=$(addsuffix .out, $(basename $(special_tests)))
-essential_results:=$(addsuffix .res, $(basename $(essential_tests)))
-extended_results:=$(addsuffix .res, $(basename $(extended_tests)))
-special_results:=$(addsuffix .res, $(basename $(special_tests)))
-
-.PHONY: all essential special extended  mkscr
-all: $(special_results)   $(special_outputs) $(extended_results)  $(extended_outputs)  $(essential_results) $(essential_outputs)  # Gnumake generally shedules the targest right to left this way long running tests (special) run first and smaller targets can fill early finished worker threads (parallel mode)
-
-essential:  $(essential_results) $(essential_outputs)
-
-extended: $(extended_results)  $(extended_outputs)
+.PRECIOUS: %.out %.res
 
 
-special:  $(special_results)   $(special_outputs)
 
-mkscr:       # is removed in the toplevel targets in the other Makefile
-	@if [ ! -d $(SCRDIR) ];\
-	then\
-	  mkdir $(SCRDIR);\
-	fi;\
+
+
